os:
  - linux

language: php

php:
  - '7.4'

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env

script:
  - vendor/bin/phpcs
  - ./vendor/bin/phpstan analyse
  - vendor/bin/phpunit --coverage-text
